spring:
  application:
    name: mail-service
  rabbitmq:
    host: 192.168.2.101
    port: 5672
    username: root
    password: 123456
    virtual-host: /
  mail:
    protocol: smtp
    host: smtp.office365.com
    port: 587
    username: test@outlook.com
    password: test
    properties:
      mail:
#        debug: true
        smtp:
          starttls:
            enable: true
#          socks:
#            host: 127.0.0.1
#            port: 7890
blog:
  from: test
  to: test