spring:
  application:
    name: mail-service
  rabbitmq:
    host: 192.168.2.101
    port: 5672
    username: root
    password: 123456
    virtual-host: /
  mail:
    host: smtp.office365.com
    port: 587
    username: 1
    password: 1
blog:
  name: "Mashiro Blog"
  mail: "1"